server:
  port: 8080
security:
  jwt:
    token:
      secret-key: 53cr37
      expire-length: 3600000
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3308/dev_vet
    username: root
    password: admin123
  jpa:
    properties:
      hibernate:
        show_sql: 'true'
        dialect: org.hibernate.dialect.MySQL8Dialect
        jdbc:
          lob:
            non_contextual_creation: 'true'
    hibernate:
      ddl-auto: update
  jackson:
    serialization:
      fail-on-empty-beans: 'false'
  server:
    error:
      whitelabel:
        enabled: 'false'